import type { NextPage } from "next";
import Head from "next/head";
import styles from "/styles/Connect.module.css";
import CustomNavbar from "/components/navbar/navbar";

import { useThemeContext } from "/context/context";

import { stream, connect } from "/firebase/webrtc";
import { auth } from "../../firebase/firebaseconf";

import { useEffect, useRef, useState } from "react";

import {
  InputGroup,
  InputGroupText,
  InputGroupAddon,
  FormInput,
  Button,
} from "shards-react";

import { useAuthState } from "react-firebase-hooks/auth";

const Home: NextPage = () => {
  const context = useThemeContext();
  const [id, setId] = useState(null);
  const [info, setInfo] = useState(null);
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  const [user, loading, error] = useAuthState(auth);
  const textInput = useRef(null);
  /* This
  const stream = async () => {
    setShowId(true);
    setStreamId(obj.id);
    setCameraOutput(obj.stream);
  };
  */

  return (
    <div className={styles.container}>
      <Head>
        <title>SecurePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{ background: context.theme === "dark" ? "#212121" : "#ffffff" }}
      >
        <CustomNavbar />
        <div
          className={`${
            context.theme === "dark"
              ? styles.dark_wrapper
              : styles.light_wrapper
          } ${styles.wrapper}`}
        >
          <div className={styles.watch_wrapper}>
            <div
              className={info ? styles.watch_wrapper_info : styles.display_none}
            >
              <b>{info ? info?.name : ""}</b>
              <p>{info ? info?.id : ""}</p>
            </div>
            <video
              className={
                context.theme === "dark"
                  ? styles.stream_video_light
                  : styles.stream_video_dark
              }
              autoPlay
            ></video>
            <InputGroup className={info ? styles.display_none : ""}>
              <FormInput
                className={styles.id_input}
                onChange={(e) => {
                  setId(e.target.value);
                }}
                placeholder="Pi id"
                size="lg"
                style={
                  context.theme === "dark"
                    ? { color: "white", background: "#232323" }
                    : {}
                }
                ref={textInput}
              />
              <InputGroupAddon type="append">
                <Button
                  theme={context.theme === "dark" ? "light" : "dark"}
                  onClick={async () => {
                    await connect(id, document, setInfo, user?.uid);
                  }}
                >
                  Gledaj
                </Button>
              </InputGroupAddon>
            </InputGroup>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Tonči Crljen &copy; 2022{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
