import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Pi-setup.module.css";
import CustomNavbar from "/components/navbar/navbar";

import { useThemeContext } from "/context/context";

import { stream, connect } from "/firebase/webrtc";

import { useEffect, useRef, useState } from "react";

import { Button } from "shards-react";

const Setup: NextPage = () => {
  const context = useThemeContext();
  const [id, setId] = useState(null);
  const [active, setActive] = useState(false);
  const videoRef = useRef(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>SecurePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{ background: context.theme === "dark" ? "#212121" : "#ffffff" }}
      >
        <CustomNavbar />
        <div
          className={`${styles.wrapper_main}
                        ${
                          context.theme === "dark"
                            ? styles.dark_wrapper
                            : styles.light_wrapper
                        }`}
        >
          <div className={`styles.video_wrapper`}>
            <video
              ref={videoRef}
              id="watchVideo"
              className={`${styles.watch_video}  ${
                context.theme === "dark"
                  ? styles.watch_video_light
                  : styles.watch_video_dark
              } ${active ? "" : styles.display_none}`}
              autoPlay
            ></video>
            <div
              className={
                active ? styles.watch_video_id_container : styles.display_none
              }
            >
              <p className={styles.watch_video_id} id="watch_video_id"></p>
              <Button id="copy_button" theme={context.theme} outline>
                Kopiraj
              </Button>
            </div>
          </div>

          <Button
            theme={context.theme === "dark" ? "light" : "dark"}
            onClick={(e) => {
              e.target.disabled = true;
              (async () => {
                let videoStream = await navigator.mediaDevices.getUserMedia({
                  video: true,
                  audio: true,
                });
                await stream(document, videoStream);
                setActive(true);
              })();
            }}
          >
            Stream video output
          </Button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Tonči Crljen &copy; 2022{" "}
        </a>
      </footer>
    </div>
  );
};

export default Setup;
