import CustomNavbar from "components/navbar/navbar";
import { useThemeContext } from "context/context";
import Head from "next/head";
import { useState } from "react";
import { Collapse } from "shards-react";
import styles from "styles/Help.module.css";

import { IoMdArrowDropdown } from "react-icons/io";
import { NodeNextRequest } from "next/dist/server/base-http/node";

const Help = () => {
  const context: { theme: string; setTheme: () => void } = useThemeContext();
  const [open, setOpen] = useState<boolean>(false);
  const [open2, setOpen2] = useState<boolean>(false);
  const [open3, setOpen3] = useState<boolean>(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>SecurePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{
          background: context.theme === "dark" ? "#212121" : "#ffffff",
        }}
      >
        <CustomNavbar />
        <div className={styles.view_one}>
          <button
            style={{
              border: "none",
              background: "none",
              cursor: "pointer",
              marginBottom: 16,
            }}
            onClick={() => setOpen(!open)}
          >
            <b style={{ color: context.theme === "dark" ? "white" : "black" }}>
              Prijenos video sadržaja s Raspberry Pia
            </b>
            <IoMdArrowDropdown
              style={{
                width: 24,
                height: 24,
                filter: context.theme === "dark" ? "invert(100%)" : "s",
                transform: open ? "rotate(0deg)" : "rotate(-90deg)",
              }}
            />
          </button>

          <Collapse open={open}>
            <p
              style={{
                color: context.theme === "dark" ? "white" : "black",
                padding: "0px 16px 16px 16px",
              }}
            >
              Prije prijenosa video sadržaja mora se osigurati stabilna
              internetska veza (preporučuje se žičana). <br />
              <br />
              Kada se prijavite u svoj korisnički račun na Raspberry Piu, morate
              stisnuti gumb "Streamaj" koji vodi na stranicu za prijenos video
              sadržaja. Nakon klika na gumb "Streamaj video sadržaj" preglednik
              vas pita za pristup kameri i mikrofonu, prihvaćanjem pokrećete
              prijenos. Iznad gumba vam se pojavljuje okvir u kojem možete
              vidjeti što prenosite te kôd koji trebate za povezivanje s drugog
              uređaja.
            </p>
          </Collapse>

          <button
            style={{
              border: "none",
              background: "none",
              cursor: "pointer",
              marginBottom: 16,
            }}
            onClick={() => setOpen2(!open2)}
          >
            <b style={{ color: context.theme === "dark" ? "white" : "black" }}>
              Povezivanje na Raspberry Pi
            </b>
            <IoMdArrowDropdown
              style={{
                width: 24,
                height: 24,
                filter: context.theme === "dark" ? "invert(100%)" : "s",
                transform: open2 ? "rotate(0deg)" : "rotate(-90deg)",
              }}
            />
          </button>

          <Collapse open={open2}>
            <p
              style={{
                color: context.theme === "dark" ? "white" : "black",
                padding: "0 16px 16px 16px",
              }}
            >
              Prijavom u svoj račun, kliknite gumb "Gledaj" koji vas vodi na
              stranicu za gledanje video sadržaja. Kako biste se mogli povezati
              sa Raspberry Piem morate znati kôd uređaja i te u polje za unos na
              stranici unesite kôd i klinite "Gledaj". Ubrzo će nestati polje za
              unos i biti će zamjenjeno okvirom u kojem se nalazi video prijenos
              kamere i ime uređaja. Napomena: korisnikov id (koji se nalazi
              stranici korisničkog računa) treba biti unutar liste dozvoljenih
              korisnika kako bi mogao pristupiti video sadržaju.
            </p>
          </Collapse>
          <button
            style={{ border: "none", background: "none", cursor: "pointer" }}
            onClick={() => setOpen3(!open3)}
          >
            <b style={{ color: context.theme === "dark" ? "white" : "black" }}>
              Promjena profilne slike
            </b>
            <IoMdArrowDropdown
              style={{
                width: 24,
                height: 24,
                filter: context.theme === "dark" ? "invert(100%)" : "",
                transform: open3 ? "rotate(0deg)" : "rotate(-90deg)",
              }}
            />
          </button>

          <Collapse open={open3}>
            <p
              style={{
                color: context.theme === "dark" ? "white" : "black",
                padding: 16,
              }}
            >
              Nakon prijave, na stranici korisničkog računa, klikom na sliku
              koja se nalazi iznad korisničkog imena i e-pošte otvara se
              dijaloški okvir u kojemu moramo stisnuti gumb "Odaberi sliku".
              Kada odaberemo, sliku možemo izrezati na željenu veličinu i
              pritisnuti gumb "Izmjeni profilnu sliku". <br />
              <br /> Ubrzo će profilna slika biti izmijenjena.
            </p>
          </Collapse>
        </div>
      </main>

      <footer
        className={styles.footer}
        style={
          context.theme === "dark"
            ? {
                backgroundColor: "#1d1d1d",
                border: "none",
                color: "white",
              }
            : {
                border: "none",
                backgroundColor: "#eee",
                color: "black",
              }
        }
      >
        Tonči Crljen &copy; 2023{" "}
      </footer>
    </div>
  );
};

export default Help;
