import type { NextPage } from "next";
import Head from "next/head";
import styles from "/styles/Connect.module.css";
import CustomNavbar from "components/navbar/navbar";

import { useThemeContext } from "context/context";

import { stream, connect } from "../../firebase/webrtc";
import { auth } from "../../firebase/firebaseconf";

import { FormEvent, useEffect, useRef, useState } from "react";

import {
  InputGroup,
  InputGroupText,
  InputGroupAddon,
  FormInput,
  Button,
} from "shards-react";

import { useAuthState } from "react-firebase-hooks/auth";

import { useRouter } from "next/router";

const Home: NextPage = () => {
  const context: { theme: string; setTheme: () => void } = useThemeContext();
  const [id, setId] = useState<null | string>(null);
  const [info, setInfo] = useState<null | {
    name: string;
    whitelist: Array<string>;
  }>(null);

  /* This
  const stream = async () => {
    setShowId(true);
    setStreamId(obj.id);
    setCameraOutput(obj.stream);
  };
  */

  const router = useRouter();

  const [user, loading, error] = useAuthState(auth);
  useEffect(() => {
    if (!user && !loading) {
      router.push("/login");
    }
    const { pid } = router.query;
    console.log(pid);
    //console.log(pid);
    if (Array.isArray(pid) && pid[0] && user) {
      console.log(pid);
      (async () => await connect(pid[0], document, setInfo, user?.uid))();
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>SecurePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{ background: context.theme === "dark" ? "#212121" : "#ffffff" }}
      >
        <CustomNavbar />
        <div
          className={`${
            context.theme === "dark"
              ? styles.dark_wrapper
              : styles.light_wrapper
          } ${styles.wrapper}`}
        >
          <div className={styles.watch_wrapper}>
            <div
              className={info ? styles.watch_wrapper_info : styles.display_none}
            >
              <b>{info ? info?.name : ""}</b>
              <p>{info ? id : ""}</p>
            </div>
            <video
              className={
                context.theme === "dark"
                  ? styles.stream_video_light
                  : styles.stream_video_dark
              }
              id="streamVideo"
              autoPlay
            ></video>
            <InputGroup className={info ? styles.display_none : ""}>
              <FormInput
                className={styles.id_input}
                onChange={(e: FormEvent<any>) => {
                  const target = e.target as HTMLInputElement;
                  target && setId(target.value);
                }}
                placeholder="Pi id"
                size="lg"
                style={
                  context.theme === "dark"
                    ? { color: "white", background: "#232323" }
                    : {}
                }
              />
              <InputGroupAddon type="append">
                <Button
                  theme={context.theme === "dark" ? "light" : "dark"}
                  onClick={async () => {
                    if (id && user)
                      await connect(id, document, setInfo, user?.uid);
                  }}
                >
                  Gledaj
                </Button>
              </InputGroupAddon>
            </InputGroup>
          </div>
        </div>
      </main>

      <footer
        className={styles.footer}
        style={
          context.theme === "dark"
            ? {
                backgroundColor: "#1d1d1d",
                border: "none",
                color: "white",
              }
            : {
                border: "none",
                backgroundColor: "#eee",
                color: "black",
              }
        }
      >
        Tonči Crljen &copy; 2023{" "}
      </footer>
    </div>
  );
};

export default Home;
