import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Connect.module.css";
import CustomNavbar from "/components/navbar/navbar";

import { useThemeContext } from "/context/context";

import { stream, connect } from "/firebase/webrtc";

import { VideoHTMLAttributes, useEffect, useRef, useState } from "react";

const Home: NextPage = () => {
  const context = useThemeContext();
  const [id, setId] = useState(null);
  const [streamId, setStreamId] = useState(null);
  const [showId, setShowId] = useState(false);
  const [cameraOutput, setCameraOutput] = useState(null);
  const [streamOutput, setStreamOutput] = useState(null);
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  /* This
  const stream = async () => {
    setShowId(true);
    setStreamId(obj.id);
    setCameraOutput(obj.stream);
  };
  */
  return (
    <div className={styles.container}>
      <Head>
        <title>SecurePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{ background: context.theme === "dark" ? "#212121" : "#ffffff" }}
      >
        <CustomNavbar />
        <div
          className={
            context.theme === "dark"
              ? styles.dark_wrapper
              : styles.light_wrapper
          }
        >
          <div className={styles.stream_wrapper}>
            <video ref={videoRef} id="watchVideo"></video>
            <button
              onClick={() => {
                (async () => {
                  let videoStream = await navigator.mediaDevices.getUserMedia({
                    video: true,
                    audio: true,
                  });
                  stream(document, videoStream);
                })();
              }}
            >
              Stream video output
            </button>
          </div>
          <div className={styles.watch_wrapper}>
            <video ref={streamRef} id="streamVideo"></video>
            <input
              onChange={(e) => {
                setId(e.target.value);
              }}
            ></input>
            <button onClick={() => connect(id, document) /*</div>connect(id)*/}>
              Watch stream
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Tonči Crljen &copy; 2022{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
