import type { NextPage } from "next";
import Head from "next/head";
import styles from "/styles/Connect.module.css";
import CustomNavbar from "/components/navbar/navbar";

import { useThemeContext } from "/context/context";

import { stream, connect } from "/firebase/webrtc";

import { useEffect, useRef, useState } from "react";

import {
  InputGroup,
  InputGroupText,
  InputGroupAddon,
  FormInput,
  Button,
} from "shards-react";

const Home: NextPage = () => {
  const context = useThemeContext();
  const [id, setId] = useState(null);
  const [streamId, setStreamId] = useState(null);
  const [showId, setShowId] = useState(false);
  const [cameraOutput, setCameraOutput] = useState(null);
  const [streamOutput, setStreamOutput] = useState(null);
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  /* This
  const stream = async () => {
    setShowId(true);
    setStreamId(obj.id);
    setCameraOutput(obj.stream);
  };
  */
  return (
    <div className={styles.container}>
      <Head>
        <title>SecurePi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{ background: context.theme === "dark" ? "#212121" : "#ffffff" }}
      >
        <CustomNavbar />
        <div
          className={`${
            context.theme === "dark"
              ? styles.dark_wrapper
              : styles.light_wrapper
          } ${styles.wrapper}`}
        >
          <div className={styles.watch_wrapper}>
            <video
              ref={streamRef}
              id="streamVideo"
              className={`${styles.stream_video} ${
                context.theme === "dark"
                  ? styles.stream_video_light
                  : styles.stream_video_dark
              }`}
            ></video>
            <InputGroup>
              <FormInput
                className={styles.id_input}
                onChange={(e) => {
                  setId(e.target.value);
                }}
                placeholder="Pi id"
                size="lg"
                style={
                  context.theme === "dark"
                    ? { color: "white", background: "#232323" }
                    : {}
                }
              />
              <InputGroupAddon type="append">
                <Button
                  theme={context.theme === "dark" ? "light" : "dark"}
                  onClick={() => connect(id, document)}
                >
                  Gledaj
                </Button>
              </InputGroupAddon>
            </InputGroup>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Tonči Crljen &copy; 2022{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
